### ISSUE TITLE
Empty Link

### ISSUE THREAD

**Issue by amayer5125** [barryWhiteHat/semaphore#4]
You say you link to a python script under section **Identitiy merkle root examples**. But the link is empty. Also the syntax for a link is `[here](LINK_URL)`.

**Comment by barryWhiteHat** [comment]
https://github.com/barryWhiteHat/semaphore/pull/6

Thanks so much for helping clean up the readme. :)

**Comment by amayer5125** [comment]
Not sure if you want another issue for this, but I found another empty link under the voting section. If you search for `[here]()` in README.md you should find it.

**Comment by amayer5125** [comment]
This issue was fixed in #6. Closing the issue.
